[build]
  base = "frontend"
  command = "npm ci && npm run build"
  publish = "dist"

[build.environment]
  NODE_ENV = "production"
  NODE_VERSION = "20"
  VITE_API_URL = "https://documind-ai.onrender.com/api"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
